blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
admin.site.site_header = "Apeksha's ecom_project"
admin.site.site_title = "Apeksha's ecom_project Portal"
admin.site.index_title = "Welcome to Apeksha's ecom_project"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace="home")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include("home.api_urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *
app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category/<slug>', ItemListView.as_view(),  name='category'),
    path('products/<slug>', ItemDetailView.as_view(), name='products'),
    path('search/', SearchView.as_view(), name='search'),
    path('contact/', contact, name='contact'),
    path('account/', signup, name='account'),
    path('review/', review_item, name='review'),
    path('cart/<slug>', cart, name='cart'),
    path('my_cart', CartView.as_view(), name='my_cart'),
    path('delete_cart/<slug>', delete_cart, name='delete_cart'),
    path('delete_single_cart/<slug>', delete_single_cart, name='delete_single_cart'),
    path('checkout', CheckoutView.as_view(), name='checkout'),
]

home/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
STATUS = (('active','active'),('','defult'))
PRODUCT_LABEL = (('new', 'new'), ('hot', 'hot'), ('most_viewed', 'most_viewed'), ('', 'default'))
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)
    image = models.CharField(max_length=200)
    status = models.CharField(default='active', choices=STATUS, max_length=100)

    def __str__(self):
        return self.title

    def get_cat_url(self):
        return reverse('home:category', kwargs={'slug': self.slug})


class Slider(models.Model):
    name = models.CharField(max_length=300)
    image = models.ImageField(upload_to='media/')
    description = models.TextField(blank=True)
    status = models.CharField(choices=STATUS, max_length=200)

    def __str__(self):
        return self.name


class Ad(models.Model):
    title = models.CharField(max_length=200)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='media/')
    status = models.CharField(default='active', choices=STATUS, max_length=100)
    rank = models.IntegerField(unique=True)

    def __str__(self):
        return self.title


class Brand(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media/')
    status = models.CharField(default='active', choices=STATUS, max_length=100)

    def __str__(self):
        return self.name


class Item(models.Model):
    item_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media/')
    slug = models.CharField(max_length=200, unique=True)
    price = models.IntegerField()
    discounted_price = models.IntegerField()
    discount = models.IntegerField()
    status = models.CharField(default='active', choices=STATUS, max_length=100)
    label = models.CharField(choices=PRODUCT_LABEL, max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    desc = models.TextField(blank=True)
    specification = models.TextField(blank=True)

    def __str__(self):
        return self.item_name

    def get_item_url(self):
        return reverse('home:products', kwargs={'slug': self.slug})

    def get_cart_url(self):
        return reverse('home:cart', kwargs={'slug': self.slug})
# when Category is deleted, Item/s also gets deleted


class Contact(models.Model):
    name = models.CharField(max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    subject = models.TextField(blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name


class Review(models.Model):
    username = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=200, blank=True)
    review = models.TextField(blank=True)
    rating = models.IntegerField()
    date_posted = models.DateTimeField(default=timezone.now)
    status = models.CharField(default='active', choices=STATUS, max_length=200)
    slug = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.username


class SiteReview(models.Model):
    name = models.CharField(max_length=200)
    profession = models.CharField(max_length=100)
    image = models.ImageField(upload_to='media/')
    status = models.CharField(default='active', choices=STATUS, max_length=100)
    review = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    username = models.CharField(max_length = 300)
    slug = models.CharField(max_length = 300)
    items = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default = 1)
    total = models.IntegerField(default = 0)
    status = models.CharField(max_length=50, choices=STATUS, default='active', null=True)
    checkout = models.BooleanField(default = False)

    def __str__(self):
        return self.username


class CartTotal(models.Model):
    username = models.CharField(max_length=200, default=None)
    net_total = models.IntegerField(default=0)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, default=None)
    slug = models.CharField(max_length=100, unique=True, default=None)
    shipping_cost = models.IntegerField(default=0)
    grand_total = models.IntegerField(default=0)
    checkout = models.BooleanField(default=False)
    date_checked = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.username


class CheckoutCart(models.Model):
    first_name = models.CharField(max_length=200, default=None)
    last_name = models.CharField(max_length=200, default=None)
    username = models.CharField(max_length=200, null=True)
    email = models.EmailField()
    shipping_add = models.CharField(max_length=200)
    mobile_no = models.IntegerField()
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    zip_code = models.CharField(max_length=20, default=None)

    def __str__(self):
        return self.first_name

home/views.py
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect

# Create your views here.
from django.template.loader import render_to_string
from django.views.generic.base import View
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.models import User
from .models import *


class BaseView(View):
        views = dict()
        views['sliders'] = Slider.objects.filter(status='active')
        views['brands'] = Brand.objects.filter(status='active')
        views['count'] = []
        for i in views['brands']:
            count_brand = Item.objects.filter(brand=i.id).count()
            g = {'name': i.name, 'count': count_brand}
            views['count'].append(g)
        views['items'] = Item.objects.filter(status='active')
        views['item_count'] = Item.objects.count()
        views['count_cat'] = Category.objects.filter(status='active')
        views['cat_count'] = []
        for i in views['count_cat']:
            count_aria = Item.objects.filter(category=i.id).count()
            h = {'name': i.title, 'image': i.image, 'count': count_aria}
            views['cat_count'].append(h)
        # simply counts all item entries in Item model/database
        views['item_count'] = Item.objects.count()


class HomeView(BaseView):
    def get(self,request):
        self.views['categories'] = Category.objects.filter(status = 'active')
        self.views['ads'] = Ad.objects.filter(status='active')
        self.views['hots'] = Item.objects.filter(label='hot')
        self.views['news'] = Item.objects.filter(label='new')
        self.views['most_viewed'] = Item.objects.filter(label='most_viewed')
        self.views['defaults'] = Item.objects.filter(label='')
        return render(request, 'index.html', self.views)


class ItemDetailView(BaseView):
    def get(self, request, slug):
        self.views['item_detail'] = Item.objects.filter(slug=slug)
        item_ids = Item.objects.get(slug=slug).category_id
        self.views['item_cats'] = Item.objects.filter(category=item_ids)
        self.views['reviews'] = Review.objects.filter(slug=slug, status='active')
        return render(request, 'product-detail.html', self.views)


class ItemListView(BaseView):
    def get(self, request, slug):
        cat_ids = Category.objects.get(slug=slug).id
        self.views['cat_items'] = Item.objects.filter(category=cat_ids)
        return render(request, 'product-list.html', self.views)


class SearchView(BaseView):
    def get(self, request):
        # query = request.GET.get('search', None)
        if request.method == 'GET':
            query = request.GET['search']
            self.views['search_product'] = Item.objects.filter(item_name__icontains=query)
            return render(request, 'search.html', self.views)
        return render(request, 'search.html')


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        data = Contact.objects.create(
            name=name,
            email=email,
            subject=subject,
            message=message
        )
        # check entered user data is correct or not by python validators
        # saves form data to DB
        if len(name) < 3 or len(subject) < 5 or len(message) < 5:
            messages.error(request, 'Please re-submit the message!')
        else:
            send_email = EmailMessage(
                'contact from your website',
                f'Hello admin, {name} is trying to contact you. His email is {email}. He want to talk about {subject}.'
                f'His message is {message}.',
                settings.EMAIL_HOST_USER,
                ['rowjune1@gmail.com'],
                [request.user.email],
            )
            send_email.fail_silently = False
            send_email.send()
            data.save()
            return redirect('/', kwargs={'messages': messages.success(request,
                                                                      '✔ Contact is saved also check your mail!')})
    return render(request, 'contact.html')


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['cpassword']
        fname = request.POST['fname']
        lname = request.POST['lname']

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.error(request, '❌ This username is already taken!')
                return redirect('home:account')
            elif User.objects.filter(email=email).exists():
                messages.error(request, '❌ This email is already taken!')
                return redirect('home:account')
            else:
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    password=password,
                    first_name=fname,
                    last_name=lname
                )
                user.save()
                messages.success(request, '✔️You are registered! Continue to login!')
                return redirect('/accounts/login', messages)
        else:
            messages.error(request, '❌ These passwords do not match!')
            return redirect('home:account')
    return render(request, 'signup.html')


def review_item(request):
    if request.method == 'POST':
        rating = request.POST['rating']
        review = request.POST['review']
        username = request.user.username
        email = request.user.email
        slug = request.POST['slug']

        user_review = Review.objects.create(
            rating=rating,
            username=username,
            review=review,
            email=email,
            slug=slug
        )
        user_review.save()
        messages.success(request, '✔️Your review is successfully submitted!')
        return redirect(f'/products/{slug}')


def cart(request, slug):
    price = Item.objects.get(slug=slug).price
    discounted_price = Item.objects.get(slug=slug).discounted_price
    user = request.user.username
    net_total = 0
    shipping_cost = 1000
    if Cart.objects.filter(slug=slug).exists():
        quantity = Cart.objects.get(username=user, slug=slug, checkout=False).quantity
        qty = quantity + 1
        if discounted_price > 0:
            actual_total = discounted_price * qty
        else:
            actual_total = price * qty
        Cart.objects.filter(username=user, slug=slug, checkout=False).update(
            quantity=qty, total=actual_total)

        total = Cart.objects.filter(username=user, checkout=False, status='active')

        for i in total[:]:
            net_total += i.total
        grand_total = net_total + shipping_cost

        CartTotal.objects.filter(username=user, checkout=False).update(
            net_total=net_total, shipping_cost=shipping_cost, grand_total=grand_total)
        return redirect('home:my_cart')

    else:
        if discounted_price > 0:
            actual_total = discounted_price * 1
        else:
            actual_total = price * 1
        data = Cart.objects.create(
            username=user,
            slug=slug,
            quantity=1,
            total=actual_total,
            items=Item.objects.filter(slug=slug)[0]

        )
        Cart.objects.filter(username=user, slug=slug, checkout=False).update(checkout=False, total=actual_total)
        total = Cart.objects.filter(username=user, checkout=False, status='active')

        for i in total[:]:
            net_total += i.total
        grand_total = net_total + shipping_cost
        data1 = CartTotal.objects.create(
            username=user,
            slug=slug,
            net_total=net_total,
            shipping_cost=shipping_cost,
            grand_total=grand_total,
            cart=Cart.objects.filter(slug=slug)[0]
        )
        data.save()
        data1.save()
        messages.success(request, f'✔️The item "{slug}" is added in cart!')
        CartTotal.objects.filter(username=user, checkout=False).update(net_total=net_total, shipping_cost=shipping_cost, grand_total=grand_total)
        return redirect('home:my_cart')


class CartView(BaseView):
    def get(self, request):
        user = request.user.username
        net_total = 0
        shipping_cost = 1000
        grand_total = 0
        self.views['cart_product'] = Cart.objects.filter(username=user, checkout=False, status='active')
        tots = CartTotal.objects.filter(username=user, checkout=False)
        for i in tots[:]:
            net_total = i.net_total
            shipping_cost = i.shipping_cost
            grand_total = i.grand_total
        self.views['cart_total'] = [{'net_total': net_total, 'shipping_cost': shipping_cost, 'grand_total': grand_total}]
        self.views['cart_count'] = Cart.objects.filter(username=user, status='active', checkout=False).count()
        return render(request, 'cart.html', self.views)


def delete_cart(request, slug):
    if Cart.objects.filter(slug=slug).exists():
        user = request.user.username
        net_total = 0
        t = 0
        shipping_cost = 1000
        grand_total = 0
        b = Cart.objects.filter(username=user, slug=slug, checkout=False, status='active')
        tots = CartTotal.objects.filter(username=user, checkout=False)
        for j in b[:]:
            t = j.total
        for i in tots[:]:
            net_total = i.net_total
            shipping_cost = i.shipping_cost
            grand_total = i.grand_total
        net_total = net_total - t
        grand_total = net_total + shipping_cost
        Cart.objects.filter(username=user, slug=slug, checkout=False).delete()
        CartTotal.objects.filter(username=user, checkout=False).update(net_total=net_total, grand_total=grand_total,

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>E Store - eCommerce HTML Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top bar Start -->
        <div class="top-bar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <i class="fa fa-envelope"></i>
                        apeksharai123@email.com
                    </div>
                    <div class="col-sm-6">
                        <i class="fa fa-phone-alt"></i>
                        9810567895
                    </div>
                </div>
            </div>
        </div>
        <!-- Top bar End -->

        <!-- Nav Bar Start -->
        <div class="nav">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="/" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'home:contact' %}" class="dropdown-item">Contact Us</a>
                        </div>
                        <div class="navbar-nav ml-auto">
                            <div class="nav-item dropdown">
                                {% if user.is_authenticated %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{ user.username }}</a>
                                <div class="dropdown-menu">
                                    <a href="/accounts/logout" class="dropdown-item">Logout</a>
                                </div>
                                {% else %}
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
                                <div class="dropdown-menu">
                                    <a href="/accounts/login" class="dropdown-item">Login</a>
                                    <a href="{% url 'home:account' %}" class="dropdown-item">Signup</a>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

        <!-- Bottom Bar Start -->
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        <div class="logo">
                            <a href="index.html">
                                <img src="{% static 'img/logo.svg' %}" style="width: 100%;" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <form method="GET" action="{% url 'home:search' %}">
                        <div class="search">
                            <input name='search' type="text" placeholder="Search">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </div>
                        </form>
                    </div>
                    <div class="col-md-3">
                        <div class="user">
                            <a href="wishlist.html" class="btn wishlist">
                                <i class="fa fa-heart"></i>
                                <span>(0)</span>
                            </a>
                            <a href="cart.html" class="btn cart">
                                <i class="fa fa-shopping-cart"></i>
                                <span>(0)</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bottom Bar End -->
        {% block content %}
        {% endblock %}

      <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Get in Touch</h2>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 django, anamnagr, kathmandu</p>
                                <p><i class="fa fa-envelope"></i>apeksharai123@gmail.com</p>
                                <p><i class="fa fa-phone"></i>9810534670</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Follow Us</h2>
                            <div class="contact-info">
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Company Info</h2>
                            <ul>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Condition</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h2>Purchase Info</h2>
                            <ul>
                                <li><a href="#">Pyament Policy</a></li>
                                <li><a href="#">Shipping Policy</a></li>
                                <li><a href="#">Return Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row payment align-items-center">
                    <div class="col-md-6">
                        <div class="payment-method">
                            <h2>We Accept:</h2>
                            <img src="img/payment-method.png" alt="Payment Method" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="payment-security">
                            <h2>Secured By:</h2>
                            <img src="img/godaddy.svg" alt="Payment Security" />
                            <img src="img/norton.svg" alt="Payment Security" />
                            <img src="img/ssl.svg" alt="Payment Security" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js'%}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

home/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          <center><strong>Message: </strong>{{ message }}</center>
        </div>
        {% endfor %}
        {% endif %}
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Products</a></li>
                    <li class="breadcrumb-item active">Contact</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->

        <!-- Contact Start -->
        <div class="contact">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="contact-info">
                            <h2>Our Office</h2>
                            <h3><i class="fa fa-map-marker"></i>django Office, anamnagar, kathmandu</h3>
                            <h3><i class="fa fa-envelope"></i>apeksharai21@gmail.com</h3>
                            <h3><i class="fa fa-phone"></i>9810568352</h3>
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="contact-info">
                            <h2>Our Store</h2>
                            <h3><i class="fa fa-map-marker"></i>django Store, naya banesawor, kathmandu</h3>
                            <h3><i class="fa fa-envelope"></i>apeksharai56@gamil.com</h3>
                            <h3><i class="fa fa-phone"></i>9834523422</h3>
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">

                        <div class="contact-form">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6">
                                        <input name='name' type="text" class="form-control" placeholder="Your Name" />
                                    </div>
                                    <div class="col-md-6">
                                        <input name="email" type="email" class="form-control" placeholder="Your Email" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input name="subject" type="text" class="form-control" placeholder="Subject" />
                                </div>
                                <div class="form-group">
                                    <textarea name="message" class="form-control" rows="5" placeholder="Message"></textarea>
                                </div>
                                <div><button class="btn" type="submit">Send Message</button></div>
                            </form>
                        </div>
                    </div>
        <!-- Contact End -->
{% endblock %}